name: 'Run ECS Task Action for GitHub Actions'
description: 'Runs a one off task on an ECS cluster'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition-arn:
    description: 'ECS task definition arn'
    required: true
  cluster:
    description: "The name of the ECS service's cluster.  Will default to the 'default' cluster"
    required: false
    default: 'default'
  count:
    description: "The number of tasks to start. Will default to 1"
    required: false
    default: 1
  wait-for-task-completion:
    description: 'Whether to wait for the ECS task to finish processing. Valid value is "true". Will default to not waiting.'
    required: false
    default: false
  wait-for-minutes:
    description: 'How long to wait for the ECS task to finish processing, in minutes (default: 30 minutes, max: 6 hours).'
    required: false
    default: 30
  overrides:
    description: 'Json object of task level overrides to use'
    required: false
  network-configuration:
    description: 'Json object of task network configuration to use'
    required: false
outputs:
  task-definition-arn:
    description: 'The ARN of the registered ECS task definition'
  task-arn-list:
    description: 'List of ARNs of the ECS task(s) run'
runs:
  using: 'node16'
  main: 'dist/index.js'
