on:
  [pull_request]

name: Check

jobs:
  check:
    name: Run Unit Tests
    runs-on: [self-hosted, linux, non-gpu]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        npm ci
        npm test
