on:
  workflow_dispatch:
    branches:
      - test-publish
    inputs:
      tag-empty-release:
        description: Tag an empty release (ex. a chore commit)
        default: false
        required: true
        type: boolean

name: Bump and Release

jobs:
  check:
    name: Package distribution file
    # For public repo's GH recommends not using self hosted
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Run Unit Tests
      run: |
        npm ci
        npm test

    - name: Create changelog and version
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.github_token }}
        skip-commit: "true"
        skip-on-empty: ${{ !inputs.tag-empty-release }}
        skip-tag: "true"
        skip-version-file: "true"
        output-file: "false"

    - name: Package and tag version
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      run: |
        git config --global user.name "GitHub Actions"
        npm version ${{ steps.changelog.outputs.version }} --no-git-tag-version -m "chore: Update dist and release %s"
        git push

    - name: Create a GitHub release
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      uses: ncipollo/release-action@58ae73b360456532aafd58ee170c045abbeaee37
      with:
        tag: ${{ steps.changelog.outputs.tag }}
        name: Release ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
