on:
  workflow_dispatch:
    branches:
      - main

name: Bump and Release

jobs:
  check:
    name: Package distribution file
    # For public repo's GH recommends not using self hosted
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Run Unit Tests
      run: |
        npm ci
        npm test

    - name: Create changelog and version
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.github_token }}
        skip-commit: "true"
        skip-version-file: "true"
        skip-commit: "true"
        skip-tag: "true"
        output-file: "false"

    - name: Package and tag version
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      run: |
        git config --global user.name "GitHub Actions"
        npm version ${{ steps.changelog.outputs.version }} -m "chore: Update dist and release %s"
        git push && git push --tags

    - name: Create a GitHub release
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      uses: ncipollo/release-action@58ae73b360456532aafd58ee170c045abbeaee37
      with:
        tag: ${{ steps.changelog.outputs.version }}
        name: Release ${{ steps.changelog.outputs.version }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
